export * as BlogCtrl from "./blogs";
export * as CategoryCtrl from "./categories";
export * as CommentCtrl from "./comments";
export * as noNameUserCtrl from "./noNameUser";
export * as LessonCtrl from "./lessons";
export * as TopicCtrl from "./topics";
export * as StudentLessonCtrl from "./student-lesson";
export * as FileCtrl from "./upload-file";
export * as ContentCtrl from "./content";
